Factory/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Factory.Models
{
  public class FactoryContextFactory : IDesignTimeDbContextFactory<FactoryContext>
  {

    FactoryContext IDesignTimeDbContextFactory<FactoryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<FactoryContext>();
      var connectionString = configuration.GetConnectionString("DefaultConnection");

      builder.UseMySql(connectionString);

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/Engineer.cs
using System.Collections.Generic;
using System;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.Machines = new HashSet<EngineerMachine>();
    }
    public int EngineerId {get;set;}
    public string Name {get;set;}
    public virtual ICollection<EngineerMachine> Machines {get;set;}
  }
}

Factory/Models/EngineerMachine.cs
namespace Factory.Models
{
  public class EngineerMachine
  {
    public int EngineerMachineId {get;set;}
    public int EngineerId {get;set;}
    public int MachineId {get;set;}
    public Engineer Engineer {get;set;}
    public Machine Machine {get;set;}
  }
}

Factory/Models/FactoryContext.cs
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public DbSet<Machine> Machines {get;set;}
    public DbSet<Engineer> Engineers {get;set;}
    public DbSet<EngineerMachine> EngineerMachine {get;set;}
    public FactoryContext(DbContextOptions options) : base(options) {}
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;
using System;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.Engineers = new HashSet<EngineerMachine>();
    }
    public int MachineId {get;set;}
    public string Name {get;set;}
    public virtual ICollection<EngineerMachine> Engineers {get;set;}
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Engineer> model = _db.Engineers.ToList();
      return View(model);
    }

    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
          .Include(engineer=>engineer.Machines)
          .ThenInclude(join=>join.Machine)
          .FirstOrDefault(engineer=>engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engi=>engi.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engi=>engi.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engi=>engi.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engi=>engi.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      var joinExists = _db.EngineerMachine.FirstOrDefault(join=>join.MachineId == MachineId && join.EngineerId == engineer.EngineerId);
      if(joinExists != null)
      {
        return RedirectToAction("Details", new {id = engineer.EngineerId});
      }

      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() {MachineId = MachineId, EngineerId = engineer.EngineerId});
      }

      _db.SaveChanges();
      return RedirectToAction("Details", new {id = engineer.EngineerId});
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry=>entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = joinEntry.EngineerId});
    }
  }
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Factory.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }
    }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
          .Include(machine=>machine.Engineers)
          .ThenInclude(join=>join.Engineer)
          .FirstOrDefault(machine=>machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine=>machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine=>machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine=>machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineer(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine=>machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int EngineerId)
    {
      var joinExists = _db.EngineerMachine.FirstOrDefault(join=>join.EngineerId == EngineerId && join.MachineId == machine.MachineId);
      if(joinExists != null)
      {
        return RedirectToAction("Details", new {id = machine.MachineId});
      }

      if(EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() {EngineerId = EngineerId, MachineId = machine.MachineId});
      }

      _db.SaveChanges();
      return RedirectToAction("Details", new {id = machine.MachineId});
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry=>entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = joinEntry.MachineId});
    }
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h1 class="jumbotron">
  Add Machine License
  <hr />
  <p>@Html.ActionLink("Engineer List", "Index") || @Html.ActionLink("Machine List", "Index", "Machines") || @Html.ActionLink("Home", "Index", "Home")</p>
</h1>
<hr />

<div class="container-fluid well">
  <h3>@Model.Name</h3>
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.EngineerId)

    @Html.Label("Select Machine")
    @Html.DropDownList("MachineId", null, new {@class = "form-control"})
    <br>
    <input type="submit" value="Save" class="btn btn-primary"/>
    <input type="button" value="Cancel" onclick="location.href='@Url.Action("Details", "Engineers", new {id=Model.EngineerId})';" class="btn btn-primary"/>
  }
</div>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer;

<h1 class="jumbotron">
  Add Engineer
  <hr />
  <p>@Html.ActionLink("Engineer List", "Index") || @Html.ActionLink("Machine List", "Index", "Machines") || @Html.ActionLink("Home", "Index", "Home")</p>
</h1>

<div class="container-fluid well">
  @using (Html.BeginForm())
  {
    <div class="form-group">
      <h4>Name</h4>
      @Html.TextBoxFor(model=>model.Name, new{@class="form-control"})
    </div>
    <input type="submit" value="Add Engineer" class="btn btn-primary">
    <input type="button" value="Cancel" onclick="location.href='@Url.Action("Index", "Engineers")';" class="btn btn-primary"/>
  }
</div>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h1 class="jumbotron">
  Delete Engineer
  <hr />
  <p>@Html.ActionLink("Engineer List", "Index") || @Html.ActionLink("Machine List", "Index", "Machines") || @Html.ActionLink("Home", "Index", "Home")</p>
</h1>
<hr />
<div class="container-fluid well">
  <h3>@Model.Name</h3>
  <h4>Are you sure you want to delete this Engineer?</h4>
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete" class="btn btn-danger"/>
    <input type="button" value="Cancel" onclick="location.href='@Url.Action("Index", "Engineers")';" class="btn btn-primary"/>
  }
</div>

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer;

<h1 class="jumbotron">
  Engineer Details
  <hr />
  <p>@Html.ActionLink("Engineer List", "Index") || @Html.ActionLink("Machine List", "Index", "Machines") || @Html.ActionLink("Home", "Index", "Home")</p>
</h1>

<div class="container-fluid well">
  <h2>Name: @Model.Name</h2>

  <hr />
  <h3>Licensed for the following machines:</h3>
  @if (@Model.Machines.Count == 0)
  {
    <h4>-No Machine Licenses Found-</h4>
  }
  else
  {
    @foreach(var join in Model.Machines)
    {
      @using (Html.BeginForm("DeleteMachine","Engineers"))
      {
        <h4>@Html.ActionLink(@join.Machine.Name, "Details", "Machines", new {id=join.MachineId}) || @Html.Hidden("joinId", @join.EngineerMachineId) <input type="submit" value="Remove" class="btn btn-primary" /></h4>
      }
    }
  }
  <br>
  <input type="button" value="Edit Engineer" onclick="location.href='@Url.Action("Edit", "Engineers", new {id = Model.EngineerId})';" class="btn btn-primary"/>
  <input type="button" value="Add Machine License" onclick="location.href='@Url.Action("AddMachine", "Engineers", new {id = Model.EngineerId})';" class="btn btn-primary"/>
</div>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer;

<h1 class="jumbotron">
  Edit Engineer
  <hr />
  <p>@Html.ActionLink("Engineer List", "Index") || @Html.ActionLink("Machine List", "Index", "Machines") || @Html.ActionLink("Home", "Index", "Home")</p>
</h1>

<div class="container-fluid well">
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model=>model.EngineerId)
    <div class="form-group">
      <h4>Name</h4>
      @Html.EditorFor(model=>model.Name, new{@class="form-control", @required=true})
    </div>
    <input type="submit" value="Save" class="btn btn-primary">
    <input type="button" value="Cancel" onclick="location.href='@Url.Action("Details", "Engineers", new {id=Model.EngineerId})';" class="btn btn-primary"/>
  }
</div>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Engineer>;

<h1 class="jumbotron">
  Engineers
  <hr />
  <p>@Html.ActionLink("Machine List", "Index", "Machines") || @Html.ActionLink("Home", "Index", "Home")</p>
</h1>

<div class="container-fluid well">
  @if (@Model.Count == 0)
  {
    <h3>No Engineers have been added yet!</h3>
  } 

  @foreach (Engineer engineer in Model)
  {
    <li>
      @Html.ActionLink($"{engineer.Name}", "Details", new {id = engineer.EngineerId}) || <input type="button" value="Delete" onclick="location.href='@Url.Action("Delete", "Engineers", new {id= engineer.EngineerId})';" class="btn btn-primary"/>
    </li>
    <br>
  }
  <br>
  <input type="button" value="New Engineer" onclick="location.href='@Url.Action("Create", "Engineers")';" class="btn btn-primary"/>
</div>

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1 class="jumbotron">
  Dr. Sneuss' Factory
  <hr />
  <p class="homeCenter">@Html.ActionLink("Engineer List", "Index", "Engineers") || @Html.ActionLink("Machine List", "Index", "Machines")</p>
</h1>
<p class="homeCenter well">Welcome to Dr. Sneuss' Factory! We specialize in all sorts of whimsical machines and gadgets, dutifully maintained by our team of licensed engineers. As a Factory Manager (congratulations on the new position, by the way) you are able to navigate to the Engineer or Machine views from the links above. From there you are able to add, edit, view, or delete records from the system. You can also assign machines to engineers with the proper licenses, as well as assign engineers to machine records if that suits you. If you have any questions or concerns, well... we don't have a support staff yet so you're on your own. Paychecks are sent out weekly if you have not setup direct deposit. Good Luck!</p>

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h1 class="jumbotron">
  Add Engineer Licensed to use this machine
  <hr />
  <p>@Html.ActionLink("Machine List", "Index") || @Html.ActionLink("Engineer List", "Index", "Engineers") || @Html.ActionLink("Home", "Index", "Home")</p>
</h1>
<hr />

<div class="container-fluid well">
  <h3>@Model.Name</h3>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.MachineId)

    @Html.Label("Select Engineer")
    @Html.DropDownList("EngineerId", null, new {@class = "form-control"})

    <input type="submit" value="Save" class="btn btn-primary"/>
  }
</div>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine;

<h1 class="jumbotron">
  Add Machine
  <hr />
  <p>@Html.ActionLink("Machine List", "Index") || @Html.ActionLink("Engineer List", "Index", "Engineers") || @Html.ActionLink("Home", "Index", "Home")</p>
</h1>

<div class="container-fluid well">
  @using (Html.BeginForm())
  {
    <div class="form-group">
      <h4>Name</h4>
      @Html.TextBoxFor(model=>model.Name, new{@class="form-control"})
    </div>
    <input type="submit" value="Add Machine" class="btn btn-primary">
    <input type="button" value="Cancel" onclick="location.href='@Url.Action("Index", "Machines")';" class="btn btn-primary"/>
  }
</div>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h1 class="jumbotron">
  Delete Machine
  <hr />
  <p>@Html.ActionLink("Machine List", "Index") || @Html.ActionLink("Engineer List", "Index", "Engineers") || @Html.ActionLink("Home", "Index", "Home")</p>
</h1>
<hr />
<div class="container-fluid well">
  <h3>@Model.Name</h3>
  <h4>Are you sure you want to delete this Machine?</h4>
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete" class="btn btn-danger"/>
    <input type="button" value="Cancel" onclick="location.href='@Url.Action("Index", "Machines")';" class="btn btn-primary"/>
  }
</div>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine;

<h1 class="jumbotron">
  Machine Details
  <hr />
  <p>@Html.ActionLink("Machine List", "Index") || @Html.ActionLink("Engineer List", "Index", "Engineers") || @Html.ActionLink("Home", "Index", "Home")</p>
</h1>

<div class="container-fluid well">
  <h2>Name: @Model.Name</h2>
  <hr />

  <h3>The Following Engineers are Licensed on this Machine:</h3>
  @if (@Model.Engineers.Count == 0)
  {
    <h4>-No Engineers Are Licensed-</h4>
  }
  else
  {
    @foreach(var join in Model.Engineers)
    {
      @using (Html.BeginForm("DeleteEngineer","Machines"))
      {
        <h4>@Html.ActionLink(@join.Engineer.Name, "Details", "Engineers", new {id=join.EngineerId}) || @Html.Hidden("joinId", @join.EngineerMachineId) <input type="submit" value="Remove" class="btn btn-primary" /></h4>
      }
    }
  }
  <br>
  <input type="button" value="Edit Machine" onclick="location.href='@Url.Action("Edit", "Machines", new {id = Model.MachineId})';" class="btn btn-primary"/>
  <input type="button" value="Add Engineer" onclick="location.href='@Url.Action("AddEngineer", "Machines", new {id = Model.MachineId})';" class="btn btn-primary"/>
</div>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine;

<h1 class="jumbotron">
  Edit Machine
  <hr />
  <p>@Html.ActionLink("Machine List", "Index") || @Html.ActionLink("Engineer List", "Index", "Engineers") || @Html.ActionLink("Home", "Index", "Home")</p>
</h1>

<div class="container-fluid well">
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model=>model.MachineId)
    <div class="form-group">
      <h4>Name</h4>
      @Html.EditorFor(model=>model.Name, new{@class="form-control", @required=true})
    </div>
    <input type="submit" value="Save" class="btn btn-primary">
    <input type="button" value="Cancel" onclick="location.href='@Url.Action("Details", "Machines", new {id=Model.MachineId})';" class="btn btn-primary"/>
  }
</div>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>;

<h1 class="jumbotron">
  Machines
  <hr />
  <p>@Html.ActionLink("Engineer List", "Index", "Engineers") || @Html.ActionLink("Home", "Index", "Home")</p>
</h1>

<div class="container-fluid well">
  @if (@Model.Count == 0)
  {
    <h3>No Machines have been added yet!</h3>
  } 

  @foreach (Machine machine in Model)
  {
    <li>
      @Html.ActionLink($"{machine.Name}", "Details", new {id = machine.MachineId}) || <input type="button" value="Delete" onclick="location.href='@Url.Action("Delete", "Machines", new {id= machine.MachineId})';" class="btn btn-primary"/>
    </li>
    <br>
  }
  <br>
  <input type="button" value="New Machine" onclick="location.href='@Url.Action("Create", "Machines")';" class="btn btn-primary"/>
</div>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Dr. Sneuss' Factory</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <div class="container">
    @RenderBody()
    </div>
  </body>
</html>